/**
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");
const baseController = require("../../lib/Controllers/BaseController");

const controller = testerlib.PlansController;
const GetPlanResponse = testerlib.GetPlanResponse;
const CreatePlanRequest = testerlib.CreatePlanRequest;
const UpdatePlanRequest = testerlib.UpdatePlanRequest;
const GetPlanItemResponse = testerlib.GetPlanItemResponse;
const CreatePlanItemRequest = testerlib.CreatePlanItemRequest;
const ListPlansResponse = testerlib.ListPlansResponse;
const UpdateMetadataRequest = testerlib.UpdateMetadataRequest;
const UpdatePlanItemRequest = testerlib.UpdatePlanItemRequest;

describe("PlansController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Gets all plans
     */
    it("should testTestGetPlans response", function testTestGetPlansTest(done) {
        // parameters for the API call
        let page = null;
        let size = null;
        let name = null;
        let status = null;
        let billingType = null;
        let createdSince = null;
        let createdUntil = null;

        controller.getPlans(page, size, name, status, billingType, createdSince, createdUntil, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            // test headers
            let headers = [];
            headers['Content-Type'] = 'application/json';
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            done();
        }).catch(() => undefined);
    });

});
