/**
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ListCardsResponse = require('../lib/Models/ListCardsResponse');
const ListInvoicesResponse = require('../lib/Models/ListInvoicesResponse');
const UpdatePriceBracketRequest = require('../lib/Models/UpdatePriceBracketRequest');
const PagingResponse = require('../lib/Models/PagingResponse');
const GetPlanItemResponse = require('../lib/Models/GetPlanItemResponse');
const GetPricingSchemeResponse = require('../lib/Models/GetPricingSchemeResponse');
const GetTokenResponse = require('../lib/Models/GetTokenResponse');
const CreateSetupRequest = require('../lib/Models/CreateSetupRequest');
const UpdateChargeCardRequest = require('../lib/Models/UpdateChargeCardRequest');
const CreatePlanItemRequest = require('../lib/Models/CreatePlanItemRequest');
const GetSafetyPayTransactionResponse = require('../lib/Models/GetSafetyPayTransactionResponse');
const UpdateMetadataRequest = require('../lib/Models/UpdateMetadataRequest');
const GetPlanResponse = require('../lib/Models/GetPlanResponse');
const GetCardTokenResponse = require('../lib/Models/GetCardTokenResponse');
const GetCheckoutCardInstallmentOptionsResponse =
  require('../lib/Models/GetCheckoutCardInstallmentOptionsResponse');
const CreatePhonesRequest = require('../lib/Models/CreatePhonesRequest');
const CreateCheckoutBoletoPaymentRequest =
  require('../lib/Models/CreateCheckoutBoletoPaymentRequest');
const CreateCardTokenRequest = require('../lib/Models/CreateCardTokenRequest');
const GetPriceBracketResponse = require('../lib/Models/GetPriceBracketResponse');
const GetBankTransferTransactionResponse =
  require('../lib/Models/GetBankTransferTransactionResponse');
const GetCheckoutPaymentSettingsResponse =
  require('../lib/Models/GetCheckoutPaymentSettingsResponse');
const ListPlansResponse = require('../lib/Models/ListPlansResponse');
const CreatePhoneRequest = require('../lib/Models/CreatePhoneRequest');
const CreateCheckoutDebitCardPaymentRequest =
  require('../lib/Models/CreateCheckoutDebitCardPaymentRequest');
const UpdatePricingSchemeRequest = require('../lib/Models/UpdatePricingSchemeRequest');
const ListAccessTokensResponse = require('../lib/Models/ListAccessTokensResponse');
const GetSetupResponse = require('../lib/Models/GetSetupResponse');
const UpdatePlanRequest = require('../lib/Models/UpdatePlanRequest');
const CreateCancelSubscriptionRequest = require('../lib/Models/CreateCancelSubscriptionRequest');
const CreateAccessTokenRequest = require('../lib/Models/CreateAccessTokenRequest');
const CreateAddressRequest = require('../lib/Models/CreateAddressRequest');
const UpdateSubscriptionBillingDateRequest =
  require('../lib/Models/UpdateSubscriptionBillingDateRequest');
const CreateCardOptionsRequest = require('../lib/Models/CreateCardOptionsRequest');
const ListTransactionsResponse = require('../lib/Models/ListTransactionsResponse');
const GetPhonesResponse = require('../lib/Models/GetPhonesResponse');
const ListCustomersResponse = require('../lib/Models/ListCustomersResponse');
const GetChargeResponse = require('../lib/Models/GetChargeResponse');
const GetOrderResponse = require('../lib/Models/GetOrderResponse');
const CreateTokenRequest = require('../lib/Models/CreateTokenRequest');
const CreateCheckoutCardInstallmentOptionRequest =
  require('../lib/Models/CreateCheckoutCardInstallmentOptionRequest');
const ListUsagesResponse = require('../lib/Models/ListUsagesResponse');
const CreatePriceBracketRequest = require('../lib/Models/CreatePriceBracketRequest');
const UpdateCardRequest = require('../lib/Models/UpdateCardRequest');
const CreateBankTransferPaymentRequest = require('../lib/Models/CreateBankTransferPaymentRequest');
const CreateVoucherPaymentRequest = require('../lib/Models/CreateVoucherPaymentRequest');
const UpdateChargeDueDateRequest = require('../lib/Models/UpdateChargeDueDateRequest');
const GetPhoneResponse = require('../lib/Models/GetPhoneResponse');
const GetVoucherTransactionResponse = require('../lib/Models/GetVoucherTransactionResponse');
const ListSubscriptionItemsResponse = require('../lib/Models/ListSubscriptionItemsResponse');
const ListOrderResponse = require('../lib/Models/ListOrderResponse');
const ListAddressesResponse = require('../lib/Models/ListAddressesResponse');
const GetCheckoutBoletoPaymentResponse = require('../lib/Models/GetCheckoutBoletoPaymentResponse');
const ListChargesResponse = require('../lib/Models/ListChargesResponse');
const ListSubscriptionsResponse = require('../lib/Models/ListSubscriptionsResponse');
const UpdatePlanItemRequest = require('../lib/Models/UpdatePlanItemRequest');
const UpdateSubscriptionItemRequest = require('../lib/Models/UpdateSubscriptionItemRequest');
const GetAntifraudResponse = require('../lib/Models/GetAntifraudResponse');
const CreateCaptureChargeRequest = require('../lib/Models/CreateCaptureChargeRequest');
const UpdateSubscriptionCardRequest = require('../lib/Models/UpdateSubscriptionCardRequest');
const CreatePlanRequest = require('../lib/Models/CreatePlanRequest');
const CreatePricingSchemeRequest = require('../lib/Models/CreatePricingSchemeRequest');
const GetDiscountResponse = require('../lib/Models/GetDiscountResponse');
const GetCustomerResponse = require('../lib/Models/GetCustomerResponse');
const CreateSubscriptionItemRequest = require('../lib/Models/CreateSubscriptionItemRequest');
const CreateOrderRequest = require('../lib/Models/CreateOrderRequest');
const GetGatewayResponseResponse = require('../lib/Models/GetGatewayResponseResponse');
const CreateDeviceRequest = require('../lib/Models/CreateDeviceRequest');
const GetRecipientResponse = require('../lib/Models/GetRecipientResponse');
const GetGatewayRecipientResponse = require('../lib/Models/GetGatewayRecipientResponse');
const GetAnticipationLimitsResponse = require('../lib/Models/GetAnticipationLimitsResponse');
const CreateBankAccountRequest = require('../lib/Models/CreateBankAccountRequest');
const GetSubscriptionItemResponse = require('../lib/Models/GetSubscriptionItemResponse');
const GetDebitCardTransactionResponse = require('../lib/Models/GetDebitCardTransactionResponse');
const CreatePaymentAuthenticationRequest =
  require('../lib/Models/CreatePaymentAuthenticationRequest');
const UpdateInvoiceStatusRequest = require('../lib/Models/UpdateInvoiceStatusRequest');
const GetAnticipationLimitResponse = require('../lib/Models/GetAnticipationLimitResponse');
const GetSubscriptionResponse = require('../lib/Models/GetSubscriptionResponse');
const UpdateOrderStatusRequest = require('../lib/Models/UpdateOrderStatusRequest');
const CreateCashPaymentRequest = require('../lib/Models/CreateCashPaymentRequest');
const CreateChargeRequest = require('../lib/Models/CreateChargeRequest');
const GetWithdrawSourceResponse = require('../lib/Models/GetWithdrawSourceResponse');
const GetAnticipationResponse = require('../lib/Models/GetAnticipationResponse');
const UpdateSubscriptionPaymentMethodRequest =
  require('../lib/Models/UpdateSubscriptionPaymentMethodRequest');
const GetBankAccountResponse = require('../lib/Models/GetBankAccountResponse');
const CreateOrderItemRequest = require('../lib/Models/CreateOrderItemRequest');
const CreateSplitOptionsRequest = require('../lib/Models/CreateSplitOptionsRequest');
const ListTransfers = require('../lib/Models/ListTransfers');
const CreateCheckoutPaymentRequest = require('../lib/Models/CreateCheckoutPaymentRequest');
const UpdateCurrentCycleStatusRequest = require('../lib/Models/UpdateCurrentCycleStatusRequest');
const GetIncrementResponse = require('../lib/Models/GetIncrementResponse');
const UpdateRecipientRequest = require('../lib/Models/UpdateRecipientRequest');
const GetBalanceResponse = require('../lib/Models/GetBalanceResponse');
const UpdateOrderItemRequest = require('../lib/Models/UpdateOrderItemRequest');
const GetGatewayErrorResponse = require('../lib/Models/GetGatewayErrorResponse');
const GetPeriodResponse = require('../lib/Models/GetPeriodResponse');
const CreateLocationRequest = require('../lib/Models/CreateLocationRequest');
const ListRecipientResponse = require('../lib/Models/ListRecipientResponse');
const GetDeviceResponse = require('../lib/Models/GetDeviceResponse');
const CreatePaymentRequest = require('../lib/Models/CreatePaymentRequest');
const GetBillingAddressResponse = require('../lib/Models/GetBillingAddressResponse');
const CreateShippingRequest = require('../lib/Models/CreateShippingRequest');
const GetCheckoutCreditCardPaymentResponse =
  require('../lib/Models/GetCheckoutCreditCardPaymentResponse');
const CreateCancelChargeSplitRulesRequest =
  require('../lib/Models/CreateCancelChargeSplitRulesRequest');
const UpdateSubscriptionStartAtRequest = require('../lib/Models/UpdateSubscriptionStartAtRequest');
const GetPrivateLabelTransactionResponse =
  require('../lib/Models/GetPrivateLabelTransactionResponse');
const GetCashTransactionResponse = require('../lib/Models/GetCashTransactionResponse');
const UpdateSubscriptionMinimumPriceRequest =
  require('../lib/Models/UpdateSubscriptionMinimumPriceRequest');
const GetTransactionReportFileResponse = require('../lib/Models/GetTransactionReportFileResponse');
const CreateClearSaleRequest = require('../lib/Models/CreateClearSaleRequest');
const CreateCheckoutCreditCardPaymentRequest =
  require('../lib/Models/CreateCheckoutCreditCardPaymentRequest');
const UpdateSubscriptionAffiliationIdRequest =
  require('../lib/Models/UpdateSubscriptionAffiliationIdRequest');
const CreateThreeDSecureRequest = require('../lib/Models/CreateThreeDSecureRequest');
const ListIncrementsResponse = require('../lib/Models/ListIncrementsResponse');
const CreateAnticipationRequest = require('../lib/Models/CreateAnticipationRequest');
const GetInvoiceItemResponse = require('../lib/Models/GetInvoiceItemResponse');
const ListAnticipationResponse = require('../lib/Models/ListAnticipationResponse');
const UpdateAddressRequest = require('../lib/Models/UpdateAddressRequest');
const GetBoletoTransactionResponse = require('../lib/Models/GetBoletoTransactionResponse');
const CreateTransferRequest = require('../lib/Models/CreateTransferRequest');
const GetUsageResponse = require('../lib/Models/GetUsageResponse');
const CreateSubscriptionRequest = require('../lib/Models/CreateSubscriptionRequest');
const CreateApplePayRequest = require('../lib/Models/CreateApplePayRequest');
const UpdateCustomerRequest = require('../lib/Models/UpdateCustomerRequest');
const CreateApplePayHeaderRequest = require('../lib/Models/CreateApplePayHeaderRequest');
const GetTransferResponse = require('../lib/Models/GetTransferResponse');
const CreateIncrementRequest = require('../lib/Models/CreateIncrementRequest');
const CreateTransfer = require('../lib/Models/CreateTransfer');
const CreateCardRequest = require('../lib/Models/CreateCardRequest');
const CreateEmvDataDukptDecryptRequest = require('../lib/Models/CreateEmvDataDukptDecryptRequest');
const CreatePrivateLabelPaymentRequest = require('../lib/Models/CreatePrivateLabelPaymentRequest');
const CreateEmvDecryptRequest = require('../lib/Models/CreateEmvDecryptRequest');
const CreateAutomaticAnticipationSettingsRequest =
  require('../lib/Models/CreateAutomaticAnticipationSettingsRequest');
const CreateAntifraudRequest = require('../lib/Models/CreateAntifraudRequest');
const PixAdditionalInformation = require('../lib/Models/PixAdditionalInformation');
const GetShippingResponse = require('../lib/Models/GetShippingResponse');
const UpdateCurrentCycleEndDateRequest = require('../lib/Models/UpdateCurrentCycleEndDateRequest');
const ListWithdrawals = require('../lib/Models/ListWithdrawals');
const GetAutomaticAnticipationResponse = require('../lib/Models/GetAutomaticAnticipationResponse');
const GetTransfer = require('../lib/Models/GetTransfer');
const UpdateChargePaymentMethodRequest = require('../lib/Models/UpdateChargePaymentMethodRequest');
const CreateDiscountRequest = require('../lib/Models/CreateDiscountRequest');
const GetCardResponse = require('../lib/Models/GetCardResponse');
const CreateBoletoPaymentRequest = require('../lib/Models/CreateBoletoPaymentRequest');
const GetLocationResponse = require('../lib/Models/GetLocationResponse');
const CreateTransferSettingsRequest = require('../lib/Models/CreateTransferSettingsRequest');
const ListTransferResponse = require('../lib/Models/ListTransferResponse');
const CreateUsageRequest = require('../lib/Models/CreateUsageRequest');
const CreateDebitCardPaymentRequest = require('../lib/Models/CreateDebitCardPaymentRequest');
const CreateCreditCardPaymentRequest = require('../lib/Models/CreateCreditCardPaymentRequest');
const ListDiscountsResponse = require('../lib/Models/ListDiscountsResponse');
const CreateRecipientRequest = require('../lib/Models/CreateRecipientRequest');
const GetTransactionResponse = require('../lib/Models/GetTransactionResponse');
const UpdateRecipientBankAccountRequest =
  require('../lib/Models/UpdateRecipientBankAccountRequest');
const UpdateTransferSettingsRequest = require('../lib/Models/UpdateTransferSettingsRequest');
const CreateCancelChargeRequest = require('../lib/Models/CreateCancelChargeRequest');
const CreateTransactionReportFileRequest =
  require('../lib/Models/CreateTransactionReportFileRequest');
const GetWithdrawTargetResponse = require('../lib/Models/GetWithdrawTargetResponse');
const CreatePixPaymentRequest = require('../lib/Models/CreatePixPaymentRequest');
const GetChargesSummaryResponse = require('../lib/Models/GetChargesSummaryResponse');
const UpdateAutomaticAnticipationSettingsRequest =
  require('../lib/Models/UpdateAutomaticAnticipationSettingsRequest');
const GetSplitResponse = require('../lib/Models/GetSplitResponse');
const ListTransactionsFilesResponse = require('../lib/Models/ListTransactionsFilesResponse');
const CreateEmvDataTlvDecryptRequest = require('../lib/Models/CreateEmvDataTlvDecryptRequest');
const CreateConfirmPaymentRequest = require('../lib/Models/CreateConfirmPaymentRequest');
const GetCheckoutDebitCardPaymentResponse =
  require('../lib/Models/GetCheckoutDebitCardPaymentResponse');
const CreateGooglePayRequest = require('../lib/Models/CreateGooglePayRequest');
const GetCheckoutBankTransferPaymentResponse =
  require('../lib/Models/GetCheckoutBankTransferPaymentResponse');
const GetUsageReportResponse = require('../lib/Models/GetUsageReportResponse');
const CreateCheckoutBankTransferRequest =
  require('../lib/Models/CreateCheckoutBankTransferRequest');
const CreateCardPaymentContactlessRequest =
  require('../lib/Models/CreateCardPaymentContactlessRequest');
const CreateCustomerRequest = require('../lib/Models/CreateCustomerRequest');
const GetTransferTargetResponse = require('../lib/Models/GetTransferTargetResponse');
const GetCheckoutPaymentResponse = require('../lib/Models/GetCheckoutPaymentResponse');
const CreateEmvDataDecryptRequest = require('../lib/Models/CreateEmvDataDecryptRequest');
const GetWithdrawResponse = require('../lib/Models/GetWithdrawResponse');
const CreateSplitRequest = require('../lib/Models/CreateSplitRequest');
const CreateInvoiceRequest = require('../lib/Models/CreateInvoiceRequest');
const GetPaymentAuthenticationResponse = require('../lib/Models/GetPaymentAuthenticationResponse');
const CreateCardPaymentContactlessPOIRequest =
  require('../lib/Models/CreateCardPaymentContactlessPOIRequest');
const CreateWithdrawRequest = require('../lib/Models/CreateWithdrawRequest');
const GetAccessTokenResponse = require('../lib/Models/GetAccessTokenResponse');
const CreateSubscriptionSplitRequest = require('../lib/Models/CreateSubscriptionSplitRequest');
const CreateInterestRequest = require('../lib/Models/CreateInterestRequest');
const CreateFineRequest = require('../lib/Models/CreateFineRequest');
const CreateGooglePayHeaderRequest = require('../lib/Models/CreateGooglePayHeaderRequest');
const GetOrderItemResponse = require('../lib/Models/GetOrderItemResponse');
const GetAddressResponse = require('../lib/Models/GetAddressResponse');
const GetTransferSourceResponse = require('../lib/Models/GetTransferSourceResponse');
const CreateSubMerchantRequest = require('../lib/Models/CreateSubMerchantRequest');
const GetPixTransactionResponse = require('../lib/Models/GetPixTransactionResponse');
const CreateCheckoutPixPaymentRequest = require('../lib/Models/CreateCheckoutPixPaymentRequest');
const GetCheckoutPixPaymentResponse = require('../lib/Models/GetCheckoutPixPaymentResponse');
const GetThreeDSecureResponse = require('../lib/Models/GetThreeDSecureResponse');
const GetCreditCardTransactionResponse = require('../lib/Models/GetCreditCardTransactionResponse');
const ListChargeTransactionsResponse = require('../lib/Models/ListChargeTransactionsResponse');
const GetInvoiceResponse = require('../lib/Models/GetInvoiceResponse');
const GetSubscriptionSplitResponse = require('../lib/Models/GetSubscriptionSplitResponse');
const GetPixPayerResponse = require('../lib/Models/GetPixPayerResponse');
const GetPixBankAccountResponse = require('../lib/Models/GetPixBankAccountResponse');
const GetInterestResponse = require('../lib/Models/GetInterestResponse');
const GetTransferSettingsResponse = require('../lib/Models/GetTransferSettingsResponse');
const CreatePeriodRequest = require('../lib/Models/CreatePeriodRequest');
const GetSplitOptionsResponse = require('../lib/Models/GetSplitOptionsResponse');
const ListCyclesResponse = require('../lib/Models/ListCyclesResponse');
const UpdateSubscriptionDueDaysRequest = require('../lib/Models/UpdateSubscriptionDueDaysRequest');
const UpdateSubscriptionSplitRequest = require('../lib/Models/UpdateSubscriptionSplitRequest');
const GetFineResponse = require('../lib/Models/GetFineResponse');
const ErrorException = require('../lib/Exceptions/ErrorException');

const classMap = {
    ListCardsResponse,
    ListInvoicesResponse,
    UpdatePriceBracketRequest,
    PagingResponse,
    GetPlanItemResponse,
    GetPricingSchemeResponse,
    GetTokenResponse,
    CreateSetupRequest,
    UpdateChargeCardRequest,
    CreatePlanItemRequest,
    GetSafetyPayTransactionResponse,
    UpdateMetadataRequest,
    GetPlanResponse,
    GetCardTokenResponse,
    GetCheckoutCardInstallmentOptionsResponse,
    CreatePhonesRequest,
    CreateCheckoutBoletoPaymentRequest,
    CreateCardTokenRequest,
    GetPriceBracketResponse,
    GetBankTransferTransactionResponse,
    GetCheckoutPaymentSettingsResponse,
    ListPlansResponse,
    CreatePhoneRequest,
    CreateCheckoutDebitCardPaymentRequest,
    UpdatePricingSchemeRequest,
    ListAccessTokensResponse,
    GetSetupResponse,
    UpdatePlanRequest,
    CreateCancelSubscriptionRequest,
    CreateAccessTokenRequest,
    CreateAddressRequest,
    UpdateSubscriptionBillingDateRequest,
    CreateCardOptionsRequest,
    ListTransactionsResponse,
    GetPhonesResponse,
    ListCustomersResponse,
    GetChargeResponse,
    GetOrderResponse,
    CreateTokenRequest,
    CreateCheckoutCardInstallmentOptionRequest,
    ListUsagesResponse,
    CreatePriceBracketRequest,
    UpdateCardRequest,
    CreateBankTransferPaymentRequest,
    CreateVoucherPaymentRequest,
    UpdateChargeDueDateRequest,
    GetPhoneResponse,
    GetVoucherTransactionResponse,
    ListSubscriptionItemsResponse,
    ListOrderResponse,
    ListAddressesResponse,
    GetCheckoutBoletoPaymentResponse,
    ListChargesResponse,
    ListSubscriptionsResponse,
    UpdatePlanItemRequest,
    UpdateSubscriptionItemRequest,
    GetAntifraudResponse,
    CreateCaptureChargeRequest,
    UpdateSubscriptionCardRequest,
    CreatePlanRequest,
    CreatePricingSchemeRequest,
    GetDiscountResponse,
    GetCustomerResponse,
    CreateSubscriptionItemRequest,
    CreateOrderRequest,
    GetGatewayResponseResponse,
    CreateDeviceRequest,
    GetRecipientResponse,
    GetGatewayRecipientResponse,
    GetAnticipationLimitsResponse,
    CreateBankAccountRequest,
    GetSubscriptionItemResponse,
    GetDebitCardTransactionResponse,
    CreatePaymentAuthenticationRequest,
    UpdateInvoiceStatusRequest,
    GetAnticipationLimitResponse,
    GetSubscriptionResponse,
    UpdateOrderStatusRequest,
    CreateCashPaymentRequest,
    CreateChargeRequest,
    GetWithdrawSourceResponse,
    GetAnticipationResponse,
    UpdateSubscriptionPaymentMethodRequest,
    GetBankAccountResponse,
    CreateOrderItemRequest,
    CreateSplitOptionsRequest,
    ListTransfers,
    CreateCheckoutPaymentRequest,
    UpdateCurrentCycleStatusRequest,
    GetIncrementResponse,
    UpdateRecipientRequest,
    GetBalanceResponse,
    UpdateOrderItemRequest,
    GetGatewayErrorResponse,
    GetPeriodResponse,
    CreateLocationRequest,
    ListRecipientResponse,
    GetDeviceResponse,
    CreatePaymentRequest,
    GetBillingAddressResponse,
    CreateShippingRequest,
    GetCheckoutCreditCardPaymentResponse,
    CreateCancelChargeSplitRulesRequest,
    UpdateSubscriptionStartAtRequest,
    GetPrivateLabelTransactionResponse,
    GetCashTransactionResponse,
    UpdateSubscriptionMinimumPriceRequest,
    GetTransactionReportFileResponse,
    CreateClearSaleRequest,
    CreateCheckoutCreditCardPaymentRequest,
    UpdateSubscriptionAffiliationIdRequest,
    CreateThreeDSecureRequest,
    ListIncrementsResponse,
    CreateAnticipationRequest,
    GetInvoiceItemResponse,
    ListAnticipationResponse,
    UpdateAddressRequest,
    GetBoletoTransactionResponse,
    CreateTransferRequest,
    GetUsageResponse,
    CreateSubscriptionRequest,
    CreateApplePayRequest,
    UpdateCustomerRequest,
    CreateApplePayHeaderRequest,
    GetTransferResponse,
    CreateIncrementRequest,
    CreateTransfer,
    CreateCardRequest,
    CreateEmvDataDukptDecryptRequest,
    CreatePrivateLabelPaymentRequest,
    CreateEmvDecryptRequest,
    CreateAutomaticAnticipationSettingsRequest,
    CreateAntifraudRequest,
    PixAdditionalInformation,
    GetShippingResponse,
    UpdateCurrentCycleEndDateRequest,
    ListWithdrawals,
    GetAutomaticAnticipationResponse,
    GetTransfer,
    UpdateChargePaymentMethodRequest,
    CreateDiscountRequest,
    GetCardResponse,
    CreateBoletoPaymentRequest,
    GetLocationResponse,
    CreateTransferSettingsRequest,
    ListTransferResponse,
    CreateUsageRequest,
    CreateDebitCardPaymentRequest,
    CreateCreditCardPaymentRequest,
    ListDiscountsResponse,
    CreateRecipientRequest,
    GetTransactionResponse,
    UpdateRecipientBankAccountRequest,
    UpdateTransferSettingsRequest,
    CreateCancelChargeRequest,
    CreateTransactionReportFileRequest,
    GetWithdrawTargetResponse,
    CreatePixPaymentRequest,
    GetChargesSummaryResponse,
    UpdateAutomaticAnticipationSettingsRequest,
    GetSplitResponse,
    ListTransactionsFilesResponse,
    CreateEmvDataTlvDecryptRequest,
    CreateConfirmPaymentRequest,
    GetCheckoutDebitCardPaymentResponse,
    CreateGooglePayRequest,
    GetCheckoutBankTransferPaymentResponse,
    GetUsageReportResponse,
    CreateCheckoutBankTransferRequest,
    CreateCardPaymentContactlessRequest,
    CreateCustomerRequest,
    GetTransferTargetResponse,
    GetCheckoutPaymentResponse,
    CreateEmvDataDecryptRequest,
    GetWithdrawResponse,
    CreateSplitRequest,
    CreateInvoiceRequest,
    GetPaymentAuthenticationResponse,
    CreateCardPaymentContactlessPOIRequest,
    CreateWithdrawRequest,
    GetAccessTokenResponse,
    CreateSubscriptionSplitRequest,
    CreateInterestRequest,
    CreateFineRequest,
    CreateGooglePayHeaderRequest,
    GetOrderItemResponse,
    GetAddressResponse,
    GetTransferSourceResponse,
    CreateSubMerchantRequest,
    GetPixTransactionResponse,
    CreateCheckoutPixPaymentRequest,
    GetCheckoutPixPaymentResponse,
    GetThreeDSecureResponse,
    GetCreditCardTransactionResponse,
    ListChargeTransactionsResponse,
    GetInvoiceResponse,
    GetSubscriptionSplitResponse,
    GetPixPayerResponse,
    GetPixBankAccountResponse,
    GetInterestResponse,
    GetTransferSettingsResponse,
    CreatePeriodRequest,
    GetSplitOptionsResponse,
    ListCyclesResponse,
    UpdateSubscriptionDueDaysRequest,
    UpdateSubscriptionSplitRequest,
    GetFineResponse,
    ErrorException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
